export const projects = [
  {
    name: "Repomind",
    slug: "repomind",
    show: "RepoMind helps you open an unfamiliar GitHub repository or a pile of docs and ask questions in plain language.",
    desc: "RepoMind is an AI-powered tool that helps you index a GitHub repository or a pile of docs and ask questions in plain language. Answers come back with the exact source file and line, so you can check the claim.",
    lang: [
      "Next.js",
      "Python",
      "Docker",
      "PgVector",
      "Voyage",
      "Groq AI",
      "Trigger.dev",
      "PostgreSQL",
      "Supabase",
    ],
    img: "repomind-img.jpg",
    vid: "repomind-video.mp4",
    img2: "repomind_img1.png",
    img3: "repomind-img3.png",
    link: "https://repomind-sandy.vercel.app/",
    git: "https://github.com/SteeveSticks/Repomind",
  },
  {
    name: "Jude Solar",
    slug: "jude-solar",
    show: "Premium solar installations for homes & businesses. Cut your electricity costs by up to 80%.",
    desc: "Delivered premium solar solutions for homes and businesses. The company provides high‑quality solar installations that can reduce electricity costs by up to 80%, offering long‑term energy independence and sustainability.",
    lang: ["React", "TypeScript", "Cloudinary", "Docker", "Whatsapp Web"],
    img: "judesolar.png",
    vid: "jude-solar.mp4",
    img2: "judesolar-img2.jpg",
    img3: "judesolar-img3.jpg",
    link: "https://www.judesolar.com/",
    git: "https://github.com/ZENDSOLV-TECHNOLOGIES-LIMITED/jude-solar",
  },
  {
    name: "StartupFounder",
    slug: "startup-founder",
    show: "Startup Founder used sanity for dynamic sections. Animated with Framer, aligning with my goal to empower developers.",
    desc: "A well-designed startup platform for developers to showcase their startups for users to discover innovative tech projects. Built using modern frameworks for speed and scalability.",
    lang: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS 4",
      "Sanity",
      "Sentry",
      "Zod",
      "NextAuth",
    ],
    img: "startupFounderimg.png",
    vid: "startup-video.mp4",
    img2: "startup-img1.jpg",
    img3: "startup-img2.jpg",
    link: "https://startup-founders-app.vercel.app/",
    git: "https://github.com/SteeveSticks/STARTUP-FULLSTACK-APP",
  },
  {
    name: "Notion App Clone",
    slug: "Notion",
    show: "Implemented real-time collaboration with user-typing indicators, using OpenAI, Cloudflare for Language, chat integration, and live features with Liveblocks and Firebase.",
    desc: "A collaborative document editing app made similar to Notion, featuring real-time user presence, typing indicators, and AI-powered chat functionality.",
    lang: [
      "Next.js",
      "Clerk",
      "Tailwind CSS",
      "Shadcn",
      "Liveblocks",
      "Firebase",
      "Hono",
      "Cloudflare Workers",
      "OpenAI API",
      "Vercel",
    ],
    img: "notionclone.png",
    vid: "notion-video.mp4",
    img2: "notion-img1.png",
    img3: "notion-img2.png",
    link: "https://notion-clone-psi-gray.vercel.app/",
    git: "https://github.com/SteeveSticks/NOTION-CLONE",
    problem:
      "Many collaborative tools lack seamless real-time interaction and advanced AI assistance, making it hard for teams to work efficiently on documents. Users often face delays in seeing edits or lack smart suggestions, reducing productivity.",
    solution:
      "I built a Notion-like clone using React with TypeScript, integrating Liveblocks for real-time collaboration and typing indicators, allowing users to see each other's edits instantly. Clerk handles user authentication and Firebase handles document storage. I added an OpenAI-like chat feature using Cloudflare Workers for language processing, enabling smart document suggestions and conversations. This solution enhances teamwork and productivity, built with a focus on real-time performance and AI-driven assistance.",
  },
];
